name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on push to the 'main' branch
      - vprofile  # Runs on push to the 'vprofile' branch

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2  # Use the stable v2 version for code checkout

      # Set up Java 11 environment (required for SonarQube scanner as of 5.x)
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Java distribution (Temurin is a popular one)
          java-version: '11'       # Java version required for your project

      # Run Maven tests
      - name: Set up Maven
        uses: actions/setup-java@v3  # Ensure Java setup is before Maven
        with:
          distribution: 'temurin'  # Choose your Java distribution
          java-version: '11'  # Specify the correct Java version

      # - name: Maven clean and test
      #   run: mvn clean test  # Run clean before testing to ensure a fresh build

      # Run Checkstyle (Java code style checker)
      - name: Checkstyle
        run: mvn checkstyle:checkstyle

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'  # Set your AWS region
        